# hash:sha256:38262e2b2b147f08ebafeb0a4ddb0016a5bc0ab2ea38aa40089d19612a4bc072
FROM registry.codeocean.com/codeocean/py-r:python3.12.8-R4.4.2-JupyterLab4.3.5-RStudiorstudio-server-2024.12.1-563-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN pip3 install -U \
    matplotlib==3.10.3 \
    numpy==2.3.1 \
    openpyxl==3.1.5 \
    pandas==2.3.1
